apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TURNeApOek16TVRCYUZ3MDBNekF4TURNeE56TXpNVEJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFERmprUHNpaWN0bFplMTVlNTNVb1djVmJDNXlGaGEyQk1iNHVNWjkrUEM3V1ZobENOQQpOVFhNaVdNTmVMbXhHbHYxQnNQdFNmcGRWK21HdWVhVU9QekkvV0UwNzZPcTFtYVU5QzB6Q0Vzd3ZHenduKytICllxVFQ2cnFiZ2lVWklHYU1yS29HMTFBTFdncC9vaHJ0aGNiTFgrT01PemxzVjR4bXhZWmQxN0VUVnozRVFYWHcKMTRBaWs3czN1NVlkbk5iL3kwdjM0YjZqQW9GeWNrcnpJWWcyNGdIemxvWEkwUlRPSzF3aDBaaFlmaHVJVUdWMQpzV2VKT0dEZHZPalhyb2c4cTJvek1Eait4MmN3ekEwZ3djMWFHYTNzcnl2TTdoMlFPWWxCbXFWN3ZHaVRIWEpyClVIaUYxTGlhamhLMDl1bTg5d1RUS1BpOTUrYU4rRFkzY3JkRkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlEwOXJ4Z1Y5eWdCZ0JhUXRFRwpRcllhU0tmUEZ6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFyMThiRXYvdU5QNWxpUDN6RXVQUHQwdWttMS9DCjVCbzFxZ2IxcTcwQW9ORk55YTAyTkduVmsvREZTcjBoOUFNMWJFTS9RSVhNVG5BVlQ4YkZyOXRjeDdlcldKT0oKdlgydnA0UHNvNEt0VkJWcXJROHZVbGpBVkl4QVN3WkZMTFp2azdaY1pQZ3ZEdzhyNkhkUTNhTHhEaHdTaU1idQpLcHVvYWluNzZoL0Rjbng1UlRvTEtKcnkzWDc4VXBseW1wRnU3ZnFGTnpwTzEvUXk0UlNsWjJEQ2poQlFpN0Y3CitpOVZYTUFNMDRmZnBUSGR3UnpmY0U2RytvcGVmS0d5R0hmYXVNLzRpQUxtbEVteFc3R0hkK3V3VE5talZ5anIKdDBvYmFPZFlnY1p3Z0VHSlU2Y0NsU0N1K1ZBbklFWkRRZzF3R0VrMk5YK0I5V0g2OEZuK3hRcWZnUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://3740657d-3f96-4233-ad58-d0a36cc37c1a.k8s.ondigitalocean.com
  name: do-lon1-k8s-prod
contexts:
- context:
    cluster: do-lon1-k8s-prod
    user: do-lon1-k8s-prod-admin
  name: do-lon1-k8s-prod
current-context: do-lon1-k8s-prod
kind: Config
preferences: {}
users:
- name: do-lon1-k8s-prod-admin
  user:
    token: ''
