apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code
  namespace: onepage
  labels:
    k8s-app: onepage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: do-block-storage
