apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: onepage
  labels:
    k8s-app: onepage
spec:
  selector:
    app: nginx
    k8s-app: onepage
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer